// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuDevice = { id: number, name: string, detail: string, vram_mb: number, fp16_storage_supported: boolean, fp16_arithmetic_supported: boolean, compute_queue_count: number, };
