// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `run_upscale` hands back: the job to track, and the path its output
 * is reserved at.
 */
export type UpscaleJobHandle = { job_id: string, output_path: string, };
