// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire shape of an [`AppError`].
 *
 * Exists as a real struct rather than a hand-rolled `serialize_struct` call
 * so the TypeScript definition can be generated from it like every other
 * IPC type, instead of being restated by hand on the other side and left to
 * drift.
 */
export type AppErrorPayload = { 
/**
 * Stable machine-readable discriminant. The frontend switches on this;
 * `message` is for humans and may be reworded freely.
 */
code: string, message: string, suggestion: string, };
