// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { default_gpu_id: number, default_scale: number, default_tile_size: number, output_directory: string | null, sound_muted: boolean, auto_check_updates: boolean, };
