// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputFormat } from "./OutputFormat";
import type { QualityPreset } from "./QualityPreset";

export type AppSettings = { 
/**
 * The Vulkan device index chosen last time.
 *
 * Retained for display and as a hint only. It must never be the thing
 * that decides which card runs a job: Vulkan's enumeration order is not
 * stable across launches on hybrid laptops. On the development machine
 * the same two devices enumerated `[0 NVIDIA][1 Intel]` and, minutes
 * later, `[0 Intel][1 NVIDIA]` -- so a saved "0" meaning the discrete
 * card silently came to mean the iGPU. `default_gpu_name` is the field
 * that survives that; see `resolveGpu` on the frontend.
 */
default_gpu_id: number, 
/**
 * The name of the device chosen last time, matched against a fresh
 * enumeration at startup. `None` for settings files written before this
 * field existed.
 */
default_gpu_name: string | null, default_scale: number, default_tile_size: number, default_preset: QualityPreset, default_output_format: OutputFormat, output_directory: string | null, sound_muted: boolean, auto_check_updates: boolean, };
