// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FullModelInfo = { id: string, name: string, note: string, cat: string, scale: number, size: string, speed: number, version: string, installed: boolean, has_update: boolean, is_corrupt: boolean, is_custom: boolean, };
