// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuTelemetry = { temperature_c: number | null, utilization_pct: number | null, memory_used_mb: number | null, memory_total_mb: number | null, fan_pct: number | null, clock_mhz: number | null, };
