// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryRecord = { file_name: string, input_path: string, output_path: string, model_name: string, scale: number, is_video: boolean, timestamp_ms: number, };
