// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobProgress = { job_id: string, percentage: number, status: string, error: string | null, phase: string | null, eta_seconds: number | null, fps: number | null, output_path: string | null, };
