// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the frontend needs to know about one job.
 *
 * A superset of the per-tick progress payload this replaces: it also carries
 * the job's inputs (so a snapshot alone is enough to render a queue row) and
 * its timestamps (so elapsed/ETA can be computed without the frontend having
 * had to witness the job start).
 */
export type JobSnapshot = { job_id: string, input_path: string, output_path: string, 
/**
 * Derived from `input_path` here rather than in the webview, so the
 * backend stays the only thing that has to know how paths are shaped.
 */
file_name: string, model_name: string, gpu_id: number, scale: number, tile_size: number, is_video: boolean, 
/**
 * One of the canonical vocabulary in `src/lib/jobState.ts`:
 * `queued` | `running` | `succeeded` | `failed` | `cancelled`.
 */
status: string, percentage: number, phase: string | null, eta_seconds: number | null, fps: number | null, error: string | null, queued_at_ms: number, started_at_ms: number | null, finished_at_ms: number | null, };
