// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobSnapshot } from "./JobSnapshot";

/**
 * The batch of jobs that changed since the last emit.
 */
export type JobsDelta = { jobs: Array<JobSnapshot>, };
