// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend needs to render a "resume this?" card.
 */
export type ResumableJob = { job_id: string, file_name: string, input_path: string, output_path: string, model_name: string, scale: number, 
/**
 * Frames verified complete on disk -- counted, not recalled.
 */
frames_done: number, };
