// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpscaleRequest = { job_id: string | null, input_path: string, 
/**
 * Where the user wants results written. `None`/empty means "alongside
 * the input". The *file name* is not the caller's concern -- the backend
 * owns naming and collision handling (see `output_paths`), and returns
 * the path it settled on.
 */
output_dir: string | null, model_id: string, gpu_id: number, scale: number, tile_size: number, is_video: boolean, };
