// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VramProfile = { total_vram_mb: number, used_vram_mb: number, safe_tile_size: number, auto_tile_size: number, proc_threads: number, thread_arg: string, is_overflowing: boolean, status_message: string, };
